### ISSUE TITLE
_ApplicationWidget mixin

### ISSUE THREAD

**Issue by craigbarker** [rishson/dojoEnterpriseApp#7]
It would be useful to have an mixin specifically at the Application widget level. 

This would provide specific functionality to alllow an application widget to autowire itself as a subscriber to any topics that are declared as publish topics from any of it's 'child' widgets.

There may be some constraints around declaritive introduction of child widgets that this mixin needs to be able to accomodate, furthermore manual registration to topics should still be possible for adhoc wiring.

**Comment by rishson** [comment]
This will need to be 2-way wiring so the 'Controller' knows about all the pubs and subs for an injected child widget.
Pseudocode:

//for declarativly created widgets
applicationWidget.injectWidget(childWidget);
iterate over childWIdget.pubList and set up subscriptions in applicationWidget
iterate over childWIdget.subList and set up publishes in applicationWidget

//for programatically created widgets
applicationWidget.adopt(childWidgetClassName, cTorParams);
call _Widget.adopt
iterate over childWIdget.pubList and set up subscriptions in applicationWidget
iterate over childWIdget.subList and set up publishes in applicationWidget
